### ISSUE TITLE
Linux build or linux compilation instructions

### ISSUE THREAD

**Issue by nitelitevtuber** [not-nullptr/Aerochat#44]
hey! 
love your project, i use linux and want a nice way to use discord without the bloat of the official client :)
is there any linux builds avaliable?

**Comment by not-nullptr** [comment]
aerochat is written in wpf which is a windows only technology. that being said, wine support for wpf has come leaps and bounds since its inception so i seriously recommend you try that! there's a few known issues under wine (namely font rendering might be pixelated, context menus appear all black) but the client is generally functional. you need to install .net 8.0 and corefonts/allfonts using winetricks jsyk

**Comment by nitelitevtuber** [comment]
Thank you! I'll experiment with that later.

**Comment by nitelitevtuber** [comment]
leaving this for people who wanna use linux:

if you are using bottles i HIGHLY suggest using wine ge proton for this, as it fixes the context menus issue :3

**Comment by bbb651** [comment]
Porting to [Avalonia](https://github.com/AvaloniaUI/Avalonia) might be a viable option, the api is pretty close ([they have a migration guide here](https://docs.avaloniaui.net/docs/get-started/wpf/)), I'm not sure how close it can be in terms of look and feel (and it's still a huge undertaking)

**Comment by not-nullptr** [comment]
> Porting to [Avalonia](https://github.com/AvaloniaUI/Avalonia) might be a viable option, the api is pretty close ([they have a migration guide here](https://docs.avaloniaui.net/docs/get-started/wpf/)), I'm not sure how close it can be in terms of look and feel (and it's still a huge undertaking)

definitely not viable. i don't have infinite time on my hands, and even if i did, there's a lot of accuracy related things i'm sure i'd struggle with in avalonia
